// <auto-generated />
using Clase6.EF.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clase6.EF.Entidades.Migrations
{
    [DbContext(typeof(JugueteriaDbContext))]
    [Migration("20261007225242_Agregando-Tematica-2")]
    partial class AgregandoTematica2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clase6.EF.Entidades.Juguete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EdadRecomendada")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TematicaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TematicaId");

                    b.ToTable("Juguetes");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Tematica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tematicas");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Juguete", b =>
                {
                    b.HasOne("Clase6.EF.Entidades.Tematica", "Tematica")
                        .WithMany("Juguetes")
                        .HasForeignKey("TematicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tematica");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Tematica", b =>
                {
                    b.Navigation("Juguetes");
                });
#pragma warning restore 612, 618
        }
    }
}
