// <auto-generated />
using Clase6.EF.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clase6.EF.Entidades.Migrations
{
    [DbContext(typeof(JugueteriaDbContext))]
    [Migration("20260527223054_AgregarFabricante")]
    partial class AgregarFabricante
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Clase6.EF.Entidades.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Juguete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EdadRecomendada")
                        .HasColumnType("int");

                    b.Property<int?>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.ToTable("Juguetes");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Juguete", b =>
                {
                    b.HasOne("Clase6.EF.Entidades.Fabricante", "Fabricante")
                        .WithMany("Juguetes")
                        .HasForeignKey("FabricanteId");

                    b.Navigation("Fabricante");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Fabricante", b =>
                {
                    b.Navigation("Juguetes");
                });
#pragma warning restore 612, 618
        }
    }
}
