// <auto-generated />
using Clase6.EF.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clase6.EF.Entidades.Migrations
{
    [DbContext(typeof(JugueteriaDbContext))]
    [Migration("20260604000956_AgregarSucursal")]
    partial class AgregarSucursal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoriaJuguete", b =>
                {
                    b.Property<int>("CategoriasId")
                        .HasColumnType("int");

                    b.Property<int>("JuguetesId")
                        .HasColumnType("int");

                    b.HasKey("CategoriasId", "JuguetesId");

                    b.HasIndex("JuguetesId");

                    b.ToTable("CategoriaJuguete");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Construcción"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Acción"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Muñecas"
                        });
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Fabricante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Fabricantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "LEGO",
                            Pais = "Dinamarca"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Hasbro",
                            Pais = "Estados Unidos"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Mattel",
                            Pais = "Estados Unidos"
                        });
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Juguete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EdadRecomendada")
                        .HasColumnType("int");

                    b.Property<int?>("FabricanteId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Juguetes");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altura = "1234",
                            Calle = "Corrientes",
                            Nombre = "Sucursal Centro"
                        },
                        new
                        {
                            Id = 2,
                            Altura = "4567",
                            Calle = "Santa Fe",
                            Nombre = "Sucursal Palermo"
                        },
                        new
                        {
                            Id = 3,
                            Altura = "890",
                            Calle = "Cabildo",
                            Nombre = "Sucursal Belgrano"
                        });
                });

            modelBuilder.Entity("CategoriaJuguete", b =>
                {
                    b.HasOne("Clase6.EF.Entidades.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clase6.EF.Entidades.Juguete", null)
                        .WithMany()
                        .HasForeignKey("JuguetesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Juguete", b =>
                {
                    b.HasOne("Clase6.EF.Entidades.Fabricante", "Fabricante")
                        .WithMany("Juguetes")
                        .HasForeignKey("FabricanteId");

                    b.HasOne("Clase6.EF.Entidades.Sucursal", "Sucursal")
                        .WithMany("Juguetes")
                        .HasForeignKey("SucursalId");

                    b.Navigation("Fabricante");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Fabricante", b =>
                {
                    b.Navigation("Juguetes");
                });

            modelBuilder.Entity("Clase6.EF.Entidades.Sucursal", b =>
                {
                    b.Navigation("Juguetes");
                });
#pragma warning restore 612, 618
        }
    }
}
